--- #YAML:1.0
name:                Wiki-Toolkit
version:             0.79
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBD::SQLite:                   0.25
    DBI:                           0
    Digest::MD5:                   0
    HTML::PullParser:              0
    Plucene:                       1.19
    Test::More:                    0
    Text::WikiFormat:              0.78
    Time::Piece:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
