# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wiki-Toolkit
version:      0.73
version_from: lib/Wiki/Toolkit.pm
installdirs:  site
requires:
    DBD::SQLite:                   0.25
    Digest::MD5:                   0
    HTML::PullParser:              0
    Plucene:                       1.19
    Test::More:                    0
    Text::WikiFormat:              0.45
    Time::Piece:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
