--- #YAML:1.0
name:               Wiki-Toolkit
version:            0.82
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:       0.25
    DBI:               0
    Digest::MD5:       0
    HTML::PullParser:  0
    Plucene:           1.19
    Test::More:        0
    Text::WikiFormat:  0.78
    Time::Piece:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
