---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wiki-Toolkit
no_index:
  directory:
    - t
    - inc
requires:
  DBD::Pg: 0
  DBD::SQLite: 0.25
  DBD::mysql: 0
  DBI: 0
  DBIx::FullTextSearch: 0.71
  Digest::MD5: 0
  HTML::PullParser: 0
  Plucene: 1.19
  Test::More: 0
  Text::WikiFormat: 0.78
  Time::Piece: 0
version: 0.84
